#!/bin/bash

PROGRAM_NAME="A6"

# Create the build folder or clean it
if [ ! -d "./build" ]
then
	mkdir build
	cd build
else
	cd build
	rm -rf *
fi

# Make the project
cmake ..
make -j

# Run it
./$PROGRAM_NAME 3 1024 out.png

