#!/bin/bash

PROGRAM_NAME="A6"

# Create the build folder or clean it
if [ ! -d "./build" ]
then
	mkdir build
	cd build
else
	cd build
	mv $PROGRAM_NAME ..
	rm -rf *
	mv ../$PROGRAM_NAME .
fi

# Configure the project in release mode
cmake -DCMAKE_BUILD_TYPE=Release ..

# Change to release mode and build
make -j

# Run it
./$PROGRAM_NAME 6 1024 out.png

eog out.png
