#!/bin/bash

PROGRAM_NAME="A6"

# Create the build folder or clean it
if [ ! -d "./build" ]
then
	mkdir build
	cd build
else
	cd build
	rm -rf *
fi

# Make the project
cmake ..
make -j

# Change to release mode
ccmake ..
make -j

# Run it
./$PROGRAM_NAME 1 1024 yum.png

eog out.png
